# Generated by Django 2.2.5 on 2020-05-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_upload',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
